### ISSUE TITLE
CI appears to be broken

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/python-crc32c#70]
I am trying to make sure we have renovate enabled in all the places we should.  I re-opened the PR here:
https://github.com/googleapis/python-crc32c/pull/8

It looks like a bunch of tests unrelated to my change are failing.  We should fix that!

**Comment by JustinBeckwith** [comment]
cc @danielduhh

**Comment by danielduhh** [comment]
Looks like the failure is related to @tseaver's [comment](https://github.com/googleapis/python-crc32c/pull/8#issuecomment-746758712) about `cffi`...

**Comment by JustinBeckwith** [comment]
This is unrelated.  The only change in that PR is the addition of a JSON file.  The auto update of the cffi package could be an issue down the road, but not in the onboarding PR.

**Comment by tseaver** [comment]
The failure (at line  for the `build-linux-3.7` [build[(https://github.com/googleapis/python-crc32c/pull/8/checks?check_run_id=3052553286) on PR #8 is due to a missing `cffi` binary wheel for **Python 3.10**.  Obviously, that CI job shouldn't be trying to build for anything *but* 3.7 (which is likely why the other builds are timing out, too).

The `scripts/manylinux/build_on_centos.sh` script needs to be tweaked to restrict the set of Python versions based on an envvar, or some such.

**Comment by tseaver** [comment]
@JustinBeckwith I have a patch in work for `scripts/manylinux/build_on_centos.sh` which would trim the build to only a specific Python version., but I don't have access to the CI configuration to set an environment variable.
